// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwtyryoxcxdjjjkjhjox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3dHlyeW94Y3hkampqa2poam94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2ODMzNjAsImV4cCI6MjA1NzI1OTM2MH0.CP_yYU43AALjv9Am6noqs56BSYeFfj_eVKlKpoblHoA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);